content:
  - name: posts
    label: Posts
    type: collection
    path: src/content
    fields: 
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, required: true }
      - { name: published, label: Published, type: boolean }
      - { name: feature, label: Published, type: boolean }
      - { name: subtitle, label: Subtitle, type: date, options: { format: 'dd MMMM yyyy' }}
      - { name: body, label: Body, type: rich-text }
  