media:
  input: public/content
  output: /content
content:
  - name: books
    label: Books
    type: collection
    path: src/content/books
    filename: "{fields.title}.json"
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: author, label: Author, type: string, required: true }
      - { name: isbn, label: ISBN, type: string, required: true }
      - { name: date, label: Date, type: date, options: { format: 'dd MMMM yyyy' }}
      - { name: published, label: Published, type: number }
      - { name: type, label: Type, type: select, options: { values: ["fiction", "non-fiction"] } }
      - { name: status, label: Status, type: select, options: { values: ["complete", "in-progress", "abandoned"] } }
      - { name: tags, label: Tags, type: select, options: { multiple: true, creatable: true } }