content:
  - name: posts
    label: Posts
    type: collection
    path: src/content
    fields: 
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: string }
      - { name: published, label: Published, type: boolean }
      - { name: subtitle, label: Subtitle, type: date, options: { format: 'DD MMMM YYYY' }}
  