name = "web"
version = "1.0.0"
target = "javascript"

[javascript]
runtime = "node"

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.5.0 and < 3.0.0"
lustre = ">= 5.7.0 and < 6.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 2.0.1 and < 3.0.0"
parz = ">= 1.1.0 and < 2.0.0"
yamleam = ">= 1.0.0 and < 2.0.0"
clip = ">= 1.2.0 and < 2.0.0"
argv = ">= 1.1.0 and < 2.0.0"
maud = ">= 2.0.0 and < 3.0.0"
mork = ">= 1.12.1 and < 2.0.0"
smalto = ">= 3.0.0 and < 4.0.0"
smalto_lustre = ">= 3.0.0 and < 4.0.0"
mork_to_lustre = ">= 1.0.0 and < 2.0.0"
jot = ">= 12.0.1 and < 13.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
glentities = ">= 6.2.1 and < 7.0.0"
