[build]
command = "pnpm run prebuild && NODE_OPTIONS=--max_old_space_size=8192 pnpm build"
publish = "_site"
base = ""

[[redirects]]
from = "https://nabeelvalley.netlify.app/*"
to = "https://nabeelvalley.co.za/:splat"
status = 301
force = true