[build]
command = "pnpm run prebuild && pnpm run build"
publish = "_site"
base = ""

[[redirects]]
from = "https://nabeelvalley.netlify.app/*"
to = "https://nabeelvalley.co.za/:splat"
status = 301
force = true