export { default as Slide } from './Slide.astro'
export { default as Presentation } from './Presentation.astro'
export { default as SlideOnly } from './SlideOnly.astro'
export { default as About } from './About.astro'
export { default as Note } from './Note.astro'
