name: Build and Release

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  build:
    defaults:
      run:
        working-directory: ./web

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: 10
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.17.0"
          rebar3-version: "3"
          # elixir-version: "1"
      - run: pnpm install
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
      - run: gleam run
      
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 
        with:
          path: web/out/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
